#!/usr/bin/env python3
"""Generate the compact DepthsPreview runtime data table from tree-core.js.

The runtime table intentionally marks a node as "reuse" only when the future
node has the same slug, category, description, and advanced description as the
live node. Changed/new nodes remain "custom" until a Lua implementation exists.
"""
from __future__ import annotations
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tree-core.js"
OUTPUT = ROOT / "game-mod" / "DepthsPreview" / "scripts" / "mods" / "DepthsPreview" / "future_data.lua"
BASE_CLASSES = ("veteran", "zealot", "psyker", "ogryn")

def norm(value):
    return re.sub(r"\s+", " ", value or "").strip()

def lua_string(value):
    value = str(value or "")
    value = value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n")
    return f'"{value}"'

def main():
    text = SOURCE.read_text(encoding="utf-8-sig").strip()
    if not text.startswith("window.TREE_DATA="):
        raise SystemExit("tree-core.js does not start with window.TREE_DATA=")
    payload = text[len("window.TREE_DATA="):]
    if payload.endswith(";"):
        payload = payload[:-1]
    data = json.loads(payload)

    out = [
        "-- AUTO-GENERATED by tools/generate_depths_preview_data.py",
        "-- Source: tree-core.js (Depths of the Damned preview + live tree)",
        "return {",
        '  schema = "20260929a",',
        f"  source_version = {lua_string(data.get('version', ''))},",
        "  classes = {",
    ]

    live_classes = {c["key"]: c for c in data.get("liveClasses", [])}
    future_classes = {c["key"]: c for c in data.get("classes", [])}

    for key in BASE_CLASSES:
        live = live_classes[key]
        future = future_classes[key]
        live_by_slug = {n["s"]: n for n in live["nodes"]}

        ordinal_count = {}
        live_ordinal = {}
        for node in live["nodes"]:
            name = norm(node.get("en")).lower()
            ordinal_count[name] = ordinal_count.get(name, 0) + 1
            live_ordinal[node["s"]] = ordinal_count[name]

        reuse = custom = 0
        out.extend([
            f"    {key} = {{",
            f"      key = {lua_string(key)},",
            "      nodes = {",
        ])
        for index, node in enumerate(future["nodes"], 1):
            stripped = re.sub(r"^depths-of-the-damned/", "", node["s"])
            live_node = live_by_slug.get(stripped)
            exact = bool(
                live_node
                and norm(live_node.get("desc")) == norm(node.get("desc"))
                and norm(live_node.get("advancedEn")) == norm(node.get("advancedEn"))
                and live_node.get("cat") == node.get("cat")
            )
            reuse += int(exact)
            custom += int(not exact)
            parts = [
                f"index = {index}",
                f"slug = {lua_string(node.get('s'))}",
                f"en = {lua_string(node.get('en'))}",
                f"cn = {lua_string(node.get('cn'))}",
                f"cat = {lua_string(node.get('cat'))}",
                f"mode = {lua_string('reuse' if exact else 'custom')}",
            ]
            if live_node:
                parts += [
                    f"live_slug = {lua_string(live_node.get('s'))}",
                    f"live_en = {lua_string(live_node.get('en'))}",
                    f"live_cn = {lua_string(live_node.get('cn'))}",
                    f"live_ordinal = {live_ordinal.get(live_node['s'], 1)}",
                ]
            out.append("        { " + ", ".join(parts) + " },")
        out.extend([
            "      },",
            f"      stats = {{ total = {len(future['nodes'])}, reuse = {reuse}, custom = {custom} }},",
            "    },",
        ])

    out.extend(["  },", "}", ""])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUTPUT}")

if __name__ == "__main__":
    main()
